#!/usr/bin/env ruby

require "pp"
require "rhubarb"
require "slop"

canon = Rhubarb::Canon.new
FREQUENCY = 20

opts = Slop.parse do |o|
  o.integer "-g", "--go", "Do a run", default: 5
  o.bool "-i", "--introduce", "Introduces Rhubarb" do
    Rhubarb::Orator.introduction
    exit
  end
  o.bool "-p", "--persona", "list off featured voices" do
    Rhubarb::Orator.persona
    exit
  end
  o.bool "-r", "--rollcall", "list off all voices" do
    Rhubarb::Orator.roll_call
    exit
  end
  o.on "--version", "print the version" do
    puts Rhubarb::VERSION
    exit
  end
end

if opts.go?
  rng = RandomNameGenerator.new
  rng_ru = RandomNameGenerator.new(RandomNameGenerator::FANTASY_RU)
  opts[:go].to_i.times do
    name = if rand(1..FREQUENCY) == 1
             rng_ru.compose
           else
             rng.compose
           end
    puts name if canon.fire(name)
  end
end
