#!/usr/bin/env ruby

require "pp"
require "rhubarb"
require "slop"

canon = Rhubarb::Canon.new

opts = Slop.parse do |o|
  o.integer "-g", "--go", "Do a run", default: 5
  o.bool "-i", "--introduce", "Introduces Rhubarb" do
    Rhubarb::Orator.introduction
    exit
  end
  o.bool "-p", "--persona", "list off featured voices" do
    Rhubarb::Orator.persona
    exit
  end
  o.bool "-r", "--rollcall", "list off all voices" do
    Rhubarb::Orator.roll_call
    exit
  end
  o.on "--version", "print the version" do
    puts Rhubarb::VERSION
    exit
  end
end

if opts.go?
  rng = RandomNameGenerator.new(RandomNameGenerator::ROMAN)
  opts[:go].to_i.times do
    name = rng.compose
    if canon.fire(name)
      puts name
    end
  end
end

# # Rhubarb::Orator.roll_call
# #
# rng = RandomNameGenerator.new(RandomNameGenerator::CURSE)
# # rng = RandomNameGenerator.new(RandomNameGenerator::ROMAN)
# # rng = RandomNameGenerator.flip_mode
#
# loop do
#   name = rng.compose
#   puts name
#   canon.name(name)
#   # canon.yo(rng.compose)
# end




